# Generated by Django 4.2 on 2023-04-11 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Atracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(help_text="nome da atração", max_length=100)),
                (
                    "descricao",
                    models.CharField(help_text="breve descrição", max_length=250),
                ),
                ("horario_abertura", models.TimeField()),
                ("horario_fechamento", models.TimeField()),
                ("idade_min", models.IntegerField(help_text="idade minima")),
            ],
        ),
    ]
