# Generated by Django 4.2 on 2023-04-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("atracoes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="atracao",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to="imagens_atracoes"
            ),
        ),
    ]
