# Generated by Django 4.2 on 2023-04-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PontoTuristico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(
                        help_text="nome do ponto turistico", max_length=100
                    ),
                ),
                (
                    "descricao",
                    models.CharField(
                        help_text="descrição breve do local", max_length=250
                    ),
                ),
                ("status", models.BooleanField(help_text="Aprovado/reprovado")),
            ],
        ),
    ]
