# Generated by Django 4.1.1 on 2023-04-13 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("enderecos", "0001_initial"),
        ("pontos_turisticos", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pontoturistico",
            name="id",
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="pontoturistico",
            name="endereco",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="enderecos.endereco"
            ),
        ),
    ]
