# Generated by Django 4.2 on 2023-04-07 00:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pontos_turisticos", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pontoturistico",
            name="status",
            field=models.BooleanField(default=False, help_text="Aprovado/reprovado"),
        ),
    ]
