# Generated by Django 4.2 on 2023-04-13 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pontos_turisticos", "0002_pontoturistico_id_alter_pontoturistico_endereco"),
    ]

    operations = [
        migrations.AddField(
            model_name="pontoturistico",
            name="imagem",
            field=models.ImageField(
                blank=True, null=True, upload_to="imagens_pontos_turisticos"
            ),
        ),
    ]
