# Generated by Django 4.2 on 2023-04-11 16:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comentarios", "0001_initial"),
        ("pontos_turisticos", "0003_pontoturistico_atracoes"),
    ]

    operations = [
        migrations.AddField(
            model_name="pontoturistico",
            name="comentarios",
            field=models.ManyToManyField(to="comentarios.comentario"),
        ),
    ]
