# Generated by Django 4.2 on 2023-04-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("avaliacoes", "0003_alter_avaliacao_estrelas"),
        ("pontos_turisticos", "0004_pontoturistico_comentarios"),
    ]

    operations = [
        migrations.AddField(
            model_name="pontoturistico",
            name="avaliacoes",
            field=models.ManyToManyField(to="avaliacoes.avaliacao"),
        ),
    ]
