# Generated by Django 4.2 on 2023-04-11 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("avaliacoes", "0001_initial"),
        ("comentarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="comentario",
            name="avaliacao",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="avaliacoes.avaliacao",
            ),
            preserve_default=False,
        ),
    ]
