# Generated by Django 4.2 on 2023-04-11 17:39

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("avaliacoes", "0002_alter_avaliacao_estrelas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avaliacao",
            name="estrelas",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("10.00")),
                ],
            ),
        ),
    ]
